export { makeLlmClient } from "./llm.js";
export { parseSectionText, spansFromInline } from "./dialect.js";
export { buildSourcePack, packForPrompt } from "./sourcePack.js";
export type { ParsedTable, PackedSource, SourcePack, EngineFile } from "./sourcePack.js";
export { evaluateAssert, auditCitations, countCitations } from "./checks.js";
export type { CheckOutcome } from "./checks.js";
export { MODEL, systemPrompt, sectionUserPrompt } from "./prompts.js";
export { draftSection } from "./draft.js";
export type { DraftCallbacks, DraftResult } from "./draft.js";
export { executeRun } from "./run.js";
export type { RunInputMsg, EngineIO, ExecuteRunResult } from "./run.js";
export { marginReply, applyEdit } from "./notesAgent.js";
export type { ProposedEdit, NoteTurn, MarginReply } from "./notesAgent.js";
